// This code was auto generated by GenerateAst.ts
import { Token } from "./Token"

abstract class Expr {
}
class Binary extends Expr {
    left: Expr;
    operator: Token;
    right: Expr;

    constructor(left: Expr, operator: Token, right: Expr){
        super();
        this.left = left;
        this.operator = operator;
        this.right = right;
    }
}
class Grouping extends Expr {
    expression: Expr;

    constructor(expression: Expr){
        super();
        this.expression = expression;
    }
}
class Literal extends Expr {
    value: Object;

    constructor(value: Object){
        super();
        this.value = value;
    }
}
class Unary extends Expr {
    operator: Token;
    right: Expr;

    constructor(operator: Token, right: Expr){
        super();
        this.operator = operator;
        this.right = right;
    }
}
